"use client"

import { useEffect, useState } from "react"
import { Loader2, Save } from "lucide-react"
import { ShopBanVeRepository } from "@/lib/shopbanve/repository"
import type { ShopContactSettings } from "@/lib/shopbanve/types"
import { useAuth } from "@/lib/firebase-auth"

type Tab = "homepage" | "contact" | "seo" | "footer" | "menu"

const defaultSettings: ShopContactSettings = {
  shopName: "Shop Bản Vẽ", email: "", phone: "", zaloEnabled: false, zaloUrl: "", zaloPhone: "", zaloMessageTemplate: "Tôi muốn hỏi về tài liệu: {title}", inquiryEnabled: true,
  contactChannels: ["zalo", "telegram", "instagram", "facebook", "email", "phone"].map((id) => ({ id: id as "zalo", label: id === "phone" ? "Điện thoại" : (id[0] || "").toUpperCase() + id.slice(1), url: "", enabled: false })),
  menuItems: [{ id: "home", label: "Trang chủ", href: "/", enabled: true, order: 1 }, { id: "catalog", label: "Danh mục tài liệu", href: "/danh-muc", enabled: true, order: 2 }, { id: "projects", label: "Dự án & đồ án", href: "/do-an", enabled: true, order: 3 }, { id: "knowledge", label: "Kiến thức", href: "/bai-viet", enabled: true, order: 4 }],
  homepageSections: [{ id: "search", label: "Tìm kiếm", enabled: true, order: 1 }, { id: "hero", label: "Hero banner", enabled: true, order: 2 }, { id: "library", label: "Thư viện tài liệu", enabled: true, order: 3 }, { id: "articles", label: "Bài viết & kiến thức", enabled: true, order: 4 }],
  homepageOptions: { showDailyUpdate: true, showCategoryLink: true, showArticleLink: true, dailyUpdateOrder: 1, categoryLinkOrder: 2, articleLinkOrder: 3 },
  announcementEnabled: true, announcementText: "TẢI BẢN VẼ NHANH CHÓNG · FILE CHUẨN KỸ THUẬT · HỖ TRỢ 24/7", footerDescription: "Nền tảng tài liệu giúp bạn tìm kiếm, học tập và làm việc với dự án hiệu quả hơn.", footerSupportTitle: "Nhận cập nhật mới", footerSupportText: "Đăng ký để không bỏ lỡ tài nguyên và bài viết hữu ích.", footerSupportButtonLabel: "Liên hệ để nhận cập nhật", seoTitle: "Shop Bản Vẽ | Kho dự án, đồ án và luận văn kỹ thuật", seoDescription: "Tìm dự án, đồ án, luận văn, bản vẽ và tài liệu tham khảo kỹ thuật theo từng chuyên ngành.", seoKeywords: "dự án xây dựng, đồ án kỹ thuật, luận văn, bản vẽ CAD, tài liệu kỹ thuật", updatedAt: "",
}

export default function ShopSettingsPage() {
  const { user } = useAuth()
  const [settings, setSettings] = useState<ShopContactSettings>(defaultSettings)
  const [tab, setTab] = useState<Tab>("homepage")
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState("")

  useEffect(() => { ShopBanVeRepository.getContactSettings().then((value) => value && setSettings({ ...defaultSettings, ...value, homepageOptions: { showDailyUpdate: value.homepageOptions?.showDailyUpdate ?? defaultSettings.homepageOptions!.showDailyUpdate, showCategoryLink: value.homepageOptions?.showCategoryLink ?? defaultSettings.homepageOptions!.showCategoryLink, showArticleLink: value.homepageOptions?.showArticleLink ?? defaultSettings.homepageOptions!.showArticleLink, dailyUpdateOrder: value.homepageOptions?.dailyUpdateOrder ?? defaultSettings.homepageOptions!.dailyUpdateOrder, categoryLinkOrder: value.homepageOptions?.categoryLinkOrder ?? defaultSettings.homepageOptions!.categoryLinkOrder, articleLinkOrder: value.homepageOptions?.articleLinkOrder ?? defaultSettings.homepageOptions!.articleLinkOrder }, homepageSections: value.homepageSections?.length ? value.homepageSections : defaultSettings.homepageSections })).catch(() => setMessage("Không thể tải cấu hình.")).finally(() => setLoading(false)) }, [])
  const update = <K extends keyof ShopContactSettings>(field: K, value: ShopContactSettings[K]) => setSettings((current) => ({ ...current, [field]: value }))
  const save = async () => { setSaving(true); setMessage(""); try { await ShopBanVeRepository.updateContactSettings(settings, user?.uid); setMessage("Đã lưu cấu hình.") } catch { setMessage("Không thể lưu cấu hình.") } finally { setSaving(false) } }
  const tabs: [Tab, string][] = [["homepage", "Trang chủ"], ["contact", "Liên hệ"], ["seo", "SEO"], ["footer", "Footer"], ["menu", "Menu"]]
  if (loading) return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin" /></div>

  return <div className="mx-auto max-w-4xl space-y-5"><header><h1 className="text-3xl font-bold text-gray-900">Cài đặt website</h1><p className="mt-1 text-gray-600">Quản lý tập trung nội dung trang chủ, liên hệ, SEO, footer và menu.</p></header><div className="flex gap-1 overflow-x-auto rounded-xl border bg-white p-1">{tabs.map(([id, label]) => <button key={id} type="button" onClick={() => setTab(id)} className={`whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-semibold ${tab === id ? "bg-blue-600 text-white" : "text-gray-600 hover:bg-gray-100"}`}>{label}</button>)}</div><section className="space-y-5 rounded-xl border bg-white p-5">
    {tab === "homepage" && <><h2 className="text-lg font-bold">Trang chủ</h2><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.announcementEnabled !== false} onChange={(e) => update("announcementEnabled", e.target.checked)} /> Hiển thị thanh thông báo đầu trang</label><label className="block text-sm font-medium">Nội dung thông báo<input value={settings.announcementText || ""} onChange={(e) => update("announcementText", e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" /></label><div className="space-y-2"><p className="text-sm font-semibold">Các khối hiển thị</p>{(settings.homepageSections || []).slice().sort((a, b) => a.order - b.order).map((item) => <div key={item.id} className="grid grid-cols-[auto_1fr_5rem] items-center gap-3 rounded-lg bg-gray-50 p-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={item.enabled} onChange={(e) => update("homepageSections", (settings.homepageSections || []).map((x) => x.id === item.id ? { ...x, enabled: e.target.checked } : x))} /> {item.label}</label><span className="text-gray-500">Thứ tự hiển thị</span><input type="number" min="1" value={item.order} onChange={(e) => update("homepageSections", (settings.homepageSections || []).map((x) => x.id === item.id ? { ...x, order: Number(e.target.value) || 1 } : x))} className="h-9 rounded-md border px-2" /></div>)}</div></>}
    {tab === "contact" && <><h2 className="text-lg font-bold">Liên hệ & form tư vấn</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Tên website<input value={settings.shopName} onChange={(e) => update("shopName", e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" /></label><label className="text-sm font-medium">Email nhận form<input value={settings.email} onChange={(e) => update("email", e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" /></label><label className="text-sm font-medium">Điện thoại<input value={settings.phone} onChange={(e) => update("phone", e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" /></label></div><div className="rounded-lg border border-orange-100 bg-orange-50 p-4"><label className="flex items-center gap-2 text-sm font-semibold text-gray-900"><input type="checkbox" checked={settings.inquiryEnabled} onChange={(e) => update("inquiryEnabled", e.target.checked)} /> Cho phép gửi yêu cầu tư vấn qua form</label><p className="mt-1 text-xs leading-5 text-gray-600">Yêu cầu tư vấn chỉ được ghi nhận khi khách điền và gửi form tại trang Liên hệ. Các nút Zalo, Telegram và mạng xã hội bên dưới chỉ là kênh liên hệ nhanh.</p></div><div className="space-y-2"><p className="text-sm font-semibold">Kênh liên hệ nhanh</p>{(settings.contactChannels || []).map((channel) => <div key={channel.id} className="grid gap-2 rounded-lg bg-gray-50 p-3 sm:grid-cols-[auto_8rem_1fr] sm:items-center"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={channel.enabled} onChange={(e) => update("contactChannels", (settings.contactChannels || []).map((x) => x.id === channel.id ? { ...x, enabled: e.target.checked } : x))} /> {channel.label}</label><span className="text-xs text-gray-500">Nút liên hệ nhanh</span><input value={channel.url} onChange={(e) => update("contactChannels", (settings.contactChannels || []).map((x) => x.id === channel.id ? { ...x, url: e.target.value } : x))} placeholder={`Link ${channel.label}`} className="h-10 rounded-md border px-3 text-sm" /></div>)}</div></>}
    {tab === "seo" && <><h2 className="text-lg font-bold">SEO</h2><label className="block text-sm font-medium">SEO title<input value={settings.seoTitle || ""} onChange={(e) => update("seoTitle", e.target.value)} maxLength={180} className="mt-1 h-10 w-full rounded-md border px-3" /></label><label className="block text-sm font-medium">SEO description<textarea value={settings.seoDescription || ""} onChange={(e) => update("seoDescription", e.target.value)} maxLength={320} className="mt-1 min-h-24 w-full rounded-md border p-3" /></label><label className="block text-sm font-medium">Từ khóa<input value={settings.seoKeywords || ""} onChange={(e) => update("seoKeywords", e.target.value)} maxLength={320} className="mt-1 h-10 w-full rounded-md border px-3" /></label></>}
    {tab === "footer" && <><h2 className="text-lg font-bold">Footer</h2><label className="block text-sm font-medium">Mô tả footer<textarea value={settings.footerDescription || ""} onChange={(e) => update("footerDescription", e.target.value)} className="mt-1 min-h-24 w-full rounded-md border p-3" /></label><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Tiêu đề hỗ trợ<input value={settings.footerSupportTitle || ""} onChange={(e) => update("footerSupportTitle", e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" /></label><label className="text-sm font-medium">Mô tả hỗ trợ<input value={settings.footerSupportText || ""} onChange={(e) => update("footerSupportText", e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" /></label><label className="text-sm font-medium">Nhãn nút<input value={settings.footerSupportButtonLabel || ""} onChange={(e) => update("footerSupportButtonLabel", e.target.value)} className="mt-1 h-10 w-full rounded-md border px-3" /></label></div></>}
    {tab === "menu" && <><h2 className="text-lg font-bold">Menu đầu trang</h2>{(settings.menuItems || []).slice().sort((a, b) => a.order - b.order).map((item) => <div key={item.id} className="grid grid-cols-[auto_1fr_5rem] items-center gap-3 rounded-lg bg-gray-50 p-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={item.enabled} onChange={(e) => update("menuItems", (settings.menuItems || []).map((x) => x.id === item.id ? { ...x, enabled: e.target.checked } : x))} /> {item.label}</label><span className="text-gray-500">{item.href}</span><input type="number" min="1" value={item.order} onChange={(e) => update("menuItems", (settings.menuItems || []).map((x) => x.id === item.id ? { ...x, order: Number(e.target.value) || 1 } : x))} className="h-9 rounded-md border px-2" /></div>)}</>}
  </section><div className="flex items-center justify-between">{message && <p role="status" className="text-sm text-emerald-700">{message}</p>}<button type="button" onClick={save} disabled={saving} className="ml-auto inline-flex min-h-11 items-center gap-2 rounded-lg bg-blue-600 px-5 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-60">{saving && <Loader2 className="h-4 w-4 animate-spin" />} Lưu cấu hình</button></div></div>
}
