"use client"
import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowUpRight, Layers3, Loader2 } from "lucide-react"
import { ShopBanVeRepository } from "@/lib/shopbanve/repository"
import type { Drawing, HomepageOptions, ShopCategory } from "@/lib/shopbanve/types"

const pageSize = 8
const fallbackImages = ["/stainless-steel-sheet-.jpg", "/stainless-steel-pipe-.jpg", "/stainless-steel-sheets-and-materials.jpg"]
function coverImage(item: Drawing) { return item.images.find((image) => image.id === item.coverImageId)?.url || item.images[0]?.url || "/placeholder.svg" }
export default function ProductsSection({ options }: { options?: HomepageOptions }) {
  const [categories, setCategories] = useState<ShopCategory[]>([]), [items, setItems] = useState<Drawing[]>([]), [page, setPage] = useState(1), [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([ShopBanVeRepository.getCategories(), ShopBanVeRepository.getPublishedDrawings()]).then(([categoryItems, drawings]) => { setCategories(categoryItems.filter((item) => item.status === "active")); setItems(drawings) }).catch(() => undefined).finally(() => setLoading(false)); return ShopBanVeRepository.onPublishedDrawingsChange(setItems) }, [])
  const totalPages = Math.max(1, Math.ceil(items.length / pageSize)), visibleItems = useMemo(() => items.slice((page - 1) * pageSize, page * pageSize), [items, page])
  const categoryCards = categories.length ? categories.slice(0, 6) : fallbackImages.map((image, index) => ({ id: `fallback-${index}`, name: ["Dự án kiến trúc", "Dự án kết cấu", "Dự án xây dựng"][index], image, order: index, status: "active" as const, createdAt: "", updatedAt: "" }))
  return <section id="danh-muc" className="bg-white py-12 sm:py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div id="do-an" className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#f97316]">Mới nhất</p><h2 className="mt-2 text-2xl font-black tracking-tight text-[#172554] sm:text-3xl">Tài liệu mới nhất</h2></div>{options?.showDailyUpdate !== false && <span className="hidden items-center gap-2 text-sm font-medium text-slate-400 sm:flex"><Layers3 className="h-4 w-4" /> Cập nhật mỗi ngày</span>}</div>{loading ? <div className="mt-6 flex min-h-40 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#f97316]" /></div> : <><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visibleItems.map((item, index) => <article key={item.id || item.slug} className="group overflow-hidden rounded-xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:border-orange-200 hover:shadow-lg"><div className="relative aspect-[1.45] overflow-hidden bg-slate-100"><img loading="lazy" src={coverImage(item)} alt={item.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" />{index === 0 && <span className="absolute left-3 top-3 rounded-md bg-[#f97316] px-2 py-1 text-[10px] font-bold text-white">MỚI</span>}</div><div className="p-4"><p className="text-[11px] font-bold uppercase tracking-wider text-[#f97316]">{item.tags[0] || "Tài liệu kỹ thuật"}</p><h3 className="mt-2 min-h-12 text-sm font-bold leading-snug text-[#172554]">{item.title}</h3><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-sm font-black text-[#f97316]">Liên hệ báo giá</span><Link href={`/ban-ve/${item.slug}`} aria-label={`Xem ${item.title}`} className="rounded-lg bg-blue-50 p-2 text-[#172554] hover:bg-[#172554] hover:text-white"><ArrowUpRight className="h-4 w-4" /></Link></div></div></article>)}</div>{visibleItems.length === 0 && <div className="mt-6 rounded-xl border border-dashed p-10 text-center text-sm text-slate-500">Chưa có tài liệu mới.</div>}<div className="mt-6 flex justify-center gap-2">{Array.from({ length: totalPages }, (_, index) => index + 1).map((number) => <button key={number} type="button" onClick={() => setPage(number)} className={`h-9 min-w-9 rounded-lg px-2 text-sm font-bold ${page === number ? "bg-[#172554] text-white" : "border border-slate-200 text-slate-500 hover:border-orange-300"}`}>{number}</button>)}</div></>}
<div className="mt-12 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#f97316]">Khám phá thư viện</p><h2 className="mt-2 text-2xl font-black tracking-tight text-[#172554] sm:text-3xl">Khám phá thư viện dự án</h2></div>{options?.showCategoryLink !== false && <Link href="/danh-muc" className="inline-flex items-center gap-2 text-sm font-bold text-[#172554] hover:text-[#f97316]">Xem tất cả danh mục <ArrowUpRight className="h-4 w-4" /></Link>}</div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categoryCards.map((category) => <Link key={category.id} href={`/danh-muc?category=${category.id}`} className="group relative min-h-44 overflow-hidden rounded-xl bg-slate-900"><img loading="lazy" src={category.image || fallbackImages[0]} alt={category.name} className="absolute inset-0 h-full w-full object-cover opacity-55 transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#172554] via-[#172554]/30 to-transparent" /><div className="absolute bottom-0 p-5 text-white"><span className="rounded-md bg-orange-100 px-2 py-1 text-[10px] font-bold text-orange-700">Danh mục tài liệu</span><h3 className="mt-3 text-lg font-bold">{category.name}</h3></div></Link>)}</div></div></section>
}
