"use client"

import Link from "next/link"
import { BookOpen, ChevronRight, CircleUserRound, CreditCard, Heart, LogOut, Settings2 } from "lucide-react"
import ShopShell from "../components/shop-shell"

export default function AccountPage() {
  return <ShopShell><section className="bg-[#172554] px-4 py-12 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-orange-500 text-2xl font-black">SB</div><div><p className="text-xs uppercase tracking-[0.2em] text-blue-200">Tài khoản của bạn</p><h1 className="mt-1 text-3xl font-black">Xin chào, thành viên</h1><p className="mt-1 text-sm text-blue-200">Khu vực quản lý tài liệu và giao dịch mẫu.</p></div></div></div></section><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="grid gap-5 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">Số dư ví</p><p className="mt-2 text-2xl font-black text-[#172554]">0đ</p><Link href="/nap-tien" className="mt-4 inline-flex text-sm font-bold text-[#f97316]">Nạp tiền <ChevronRight className="h-4 w-4" /></Link></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">Tài liệu đã lưu</p><p className="mt-2 text-2xl font-black text-[#172554]">0</p><span className="mt-4 inline-flex text-sm text-slate-400">Đang cập nhật</span></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">Yêu cầu tư vấn</p><p className="mt-2 text-2xl font-black text-[#172554]">0</p><span className="mt-4 inline-flex text-sm text-slate-400">Đang cập nhật</span></div></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[[BookOpen,"Tài liệu của tôi","Quản lý tài liệu đã mua hoặc lưu."],[Heart,"Yêu thích","Danh sách dự án bạn quan tâm."],[CreditCard,"Lịch sử nạp tiền","Theo dõi giao dịch trong tương lai."],[CircleUserRound,"Thông tin cá nhân","Cập nhật hồ sơ thành viên."],[Settings2,"Cài đặt tài khoản","Tùy chỉnh trải nghiệm cá nhân."],[LogOut,"Đăng xuất","Tính năng sẽ kết nối sau."]].map(([Icon,title,description]) => { const ItemIcon = Icon as typeof BookOpen; return <button type="button" key={title as string} className="flex items-start gap-4 rounded-2xl border border-slate-200 bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-orange-200 hover:shadow-lg"><span className="rounded-xl bg-orange-50 p-3 text-[#f97316]"><ItemIcon className="h-5 w-5" /></span><span><b className="block text-[#172554]">{title as string}</b><small className="mt-1 block leading-5 text-slate-500">{description as string}</small></span></button> })}</div></section></ShopShell>
}
